### ISSUE TITLE
oneapi analysis出错

### ISSUE THREAD

**Issue by wxyShine** [tudou527/OneAPI#19]
```log
[09:12:56] class: com.ruoyi.web.domain.Vehicle
[09:12:56]   field count: 49
[09:12:56]     addressName: String
[09:12:56]     platformName: String
[09:12:56]     fullName: String
[09:12:56]     vehicleId: Long
[09:12:56]     operationType: String
[09:12:56]     merchantCode: String
[09:12:56]     plateNumber: String
[09:12:56]     plateColor: String
[09:12:56]     energyType: String
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.oneapi.spring.utils.ClassUtil.lambda$getAnnotation$3(ClassUtil.java:123)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at com.oneapi.spring.utils.ClassUtil.lambda$getAnnotation$4(ClassUtil.java:62)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.oneapi.spring.utils.ClassUtil.getAnnotation(ClassUtil.java:46)
        at com.oneapi.spring.analysis.BasicAnalysis.lambda$getFieldList$3(BasicAnalysis.java:226)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.oneapi.spring.analysis.BasicAnalysis.getFieldList(BasicAnalysis.java:211)
        at com.oneapi.spring.analysis.BasicAnalysis.analysisClass(BasicAnalysis.java:198)
        at com.oneapi.spring.analysis.BasicAnalysis.analysisFromResource(BasicAnalysis.java:123)
        at com.oneapi.spring.analysis.BasicAnalysis.analysis(BasicAnalysis.java:62)
        at com.oneapi.spring.Application.lambda$analysisClassReference$3(Application.java:147)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.oneapi.spring.Application.analysisClassReference(Application.java:146)
        at com.oneapi.spring.Application.run(Application.java:114)
        at com.oneapi.spring.Application.main(Application.java:178)
```

**Comment by tudou527** [comment]
@wxyShine 方便把你的 com.ruoyi.web.domain.Vehicle 这个class 文件邮件发我一份吗 tudou527#gmail.com

**Comment by wxyShine** [comment]
> tudou527#[gmail.com](https://gmail.com)

已发送
